# Generated by Django 5.1.3 on 2026-09-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_post_author_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_angel",
            field=models.BooleanField(
                default=False, verbose_name="آیا مربوط به حالت فرشته است؟"
            ),
        ),
    ]
